import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useFormik } from "formik";

const inter = Inter({ subsets: ["latin"] });

import { Heading, Text, Box, FormControl, FormLabel, FormErrorMessage, FormHelperText, Input, Button } from "@chakra-ui/react";

export default function Home() {
  const formik = useFormik({
    initialValues: {
      email: "",
    },
    onSubmit: (values) => {
      alert(JSON.stringify(values, null, 2));
    },
  });

  return (
    <>
      <Head>
        <title>PM Bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box w="100%" maxW={960} marginInline="auto" gap={4}>
          <Heading>PM AI Bot</Heading>
          <Text>Intro copy</Text>
          <Box maxW={480} gap={4}>
            <form onSubmit={formik.handleSubmit}>
              <FormControl>
                <FormLabel>Email address</FormLabel>
                <Input type="email" />
              </FormControl>

              <Button type="submit">Submit</Button>
            </form>
          </Box>
        </Box>
      </main>
    </>
  );
}
